server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
